name: lazyloading_getx_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  lazy_load_scrollview: 1.3.0
  get: ^4.6.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.0
  shimmer: ^2.0.0
  easy_image_viewer: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:

  uses-material-design: true

  assets:
    - assets/void.png
    - assets/warning.png
    - assets/logo.png